[package]
name = "serde-beve"
version = "1.0.0"
edition = "2024"

[dependencies]
serde = "1.0.219"
thiserror = "2.0.12"
serde_json = "1.0.140"
half = { version = "2.6.0", optional = true }

[features]
default = []
half = ["dep:half"]
